/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2sdcasdscdcsd3i_glb.glb --transform 
Files: 2sdcasdscdcsd3i_glb.glb [5.95MB] > /home/linuxlite/wwwww/public/2sdcasdscdcsd3i_glb-transformed.glb [202.57KB] (97%)
Author: Alex.Bellesia (https://sketchfab.com/Alex.Bellesia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2sdcasdscdcsd3i-glb-b861bcc2fe984dde992fccd0c10f09f0
Title: 2sdcasdscdcsd3I_glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2sdcasdscdcsd3i_glb-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.TexMap} scale={0.72} />
    </group>
  )
}

useGLTF.preload('/2sdcasdscdcsd3i_glb-transformed.glb')
