/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fiesta_tea-transformed.glb --transform 
Files: fiesta_tea-transformed.glb [2.28MB] > /home/linuxlite/wwwww/public/fiesta_tea-transformed-transformed.glb [766.48KB] (66%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fiesta_tea-transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_28.geometry} material={materials.peripheri_Base_Color} position={[-0.238, 1, 0.665]} scale={0.625} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.trad_edges} position={[0, 0.316, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['table_Base_Color.002']} position={[0, 0.316, 0]} scale={0.69} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.teapot_glass_Base_Color} position={[-0.908, 1.351, 0.038]} />
    </group>
  )
}

useGLTF.preload('/fiesta_tea-transformed-transformed.glb')
