/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new.glb --transform 
Files: new.glb [2.24MB] > /home/linuxlite/wwwww/public/new-transformed.glb [195.33KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={materials['Material.001']} position={[0, 1.432, 0]} scale={[1, 1, 1.059]} />
    </group>
  )
}

useGLTF.preload('/new-transformed.glb')
