/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wwwww.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['Material.004']}
        position={[0, 1.128, 0.001]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.496}
      />
    </group>
  )
}

useGLTF.preload('/wwwww.gltf')


// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/wwwww.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Suzanne.geometry}
//         // material={materials['Material.001']}
//       />
//     </group>
//   )
// }

// useGLTF.preload('/untitled.gltf')

